os: osx
language: c
compiler:
  - gcc

# env:
  # global:
    # - DART_SDK_FILENAME: dartsdk-macos-x64-release.zip
    # - DART_SDK_CHANNEL: stable
    # - DART_SDK_VERSION: 2.7.0
    # - DART_SDK: ${TRAVIS_HOME}/dart-sdk
    
install: 
  - echo ${TRAVIS_HOME}
  - ls -l ${TRAVIS_HOME}
  - chmod -R ugo+x scripts/
  - bash ${TRAVIS_BUILD_DIR}/scripts/downloadDart.sh
# - mkdir -p ${TRAVIS_HOME}/Downloads/
# - curl --connect-timeout 15 --retry 5 -o ${TRAVIS_HOME}/Downloads/${DART_SDK_FILENAME} -O https://storage.googleapis.com/dart-archive/channels/${DART_SDK_CHANNEL}/release/${DART_SDK_VERSION}/sdk/${DART_SDK_FILENAME}
# - unzip ${TRAVIS_HOME}/Downloads/${DART_SDK_FILENAME} -d ${TRAVIS_HOME}/
# - export PATH=$PATH:${DART_SDK}/bin
# - dart --version

before_script:
  - mkdir build
  - pushd build
  - cmake -S ..  
  
script: 
  - make #make && make test #TODO: Add native tests
  - popd
    
after_success: ${TRAVIS_BUILD_DIR}/scripts/runDart.sh
