os: osx
language: c
compiler:
  - gcc

env:
  global:
    - DART_SDK: ${HOME}/dart-sdk
    
install: 
  - chmod -R ugo+x ${TRAVIS_BUILD_DIR}/scripts/
  - ${TRAVIS_BUILD_DIR}/scripts/downloadDart.sh

before_script:
  - mkdir build
  - pushd build
  - cmake -S ..  
  
script: 
  - make #make && make test #TODO: Add native tests
  - popd
    
after_success: ${TRAVIS_BUILD_DIR}/scripts/runDart.sh
